version: '3.8'

services:
  bitsacco-whatsapp-bot:
    build: .
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bitsacco-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - bitsacco-whatsapp-bot
    restart: unless-stopped
    networks:
      - bitsacco-network

networks:
  bitsacco-network:
    driver: bridge

volumes:
  ssl_certs:
    driver: local
